/* ========================================
   Infinite Compliment Machine
   1000+ Personalized Compliments
   ======================================== */

const ComplimentDB = {
    // Base compliments that work for anyone
    universal: [
        "You're doing better than you think you are.",
        "The world is genuinely brighter because you exist.",
        "Your kindness creates ripples you'll never see.",
        "You have a unique magic that only you bring.",
        "Someone smiled today because of something you did.",
        "You're stronger than your hardest day.",
        "Your presence is a present to those around you.",
        "You make difficult things look effortless.",
        "The way you care about things is beautiful.",
        "You're exactly who someone needs right now.",
        "Your potential is limitless and exciting.",
        "You bring out the best in people.",
        "Your thoughts and feelings matter deeply.",
        "You're growing in ways you can't even see yet.",
        "The effort you put in doesn't go unnoticed.",
        "You have a gift for making people feel seen.",
        "Your resilience is quietly inspiring.",
        "You're worthy of all the good things coming your way.",
        "Your authenticity is refreshing and rare.",
        "You handle challenges with remarkable grace.",
        "Your smile could light up the darkest room.",
        "You're a work of art in progress.",
        "Your voice deserves to be heard.",
        "You make ordinary moments feel special.",
        "Your capacity for love is extraordinary.",
        "You're braver than you believe.",
        "Your contributions matter, big and small.",
        "You have a heart of pure gold.",
        "Your journey is uniquely beautiful.",
        "You inspire others just by being you.",
        "Your wisdom comes from lived experience.",
        "You're someone people can count on.",
        "Your optimism is contagious.",
        "You have incredible inner strength.",
        "Your empathy makes the world softer.",
        "You're capable of amazing things.",
        "Your laughter is music to the ears.",
        "You bring positive energy wherever you go.",
        "Your perspective is valuable and needed.",
        "You're making progress even when it doesn't feel like it.",
        "Your generosity knows no bounds.",
        "You have a beautiful soul.",
        "Your determination is admirable.",
        "You're loved more than you know.",
        "Your creativity knows no limits.",
        "You handle stress with impressive composure.",
        "Your intuition is spot-on.",
        "You're a beacon of hope for others.",
        "Your patience is a superpower.",
        "You make people feel welcome and valued.",
        "Your courage inspires those around you.",
        "You're thoughtful in ways that matter.",
        "Your enthusiasm is infectious.",
        "You have a natural talent for connection.",
        "Your hard work is paying off.",
        "You're deserving of rest and celebration.",
        "Your honesty is refreshing.",
        "You bring joy to everyday moments.",
        "Your intelligence shines in everything you do.",
        "You're a true friend to those who know you.",
        "Your passion is beautiful to witness.",
        "You handle setbacks with dignity.",
        "Your warmth makes people feel at home.",
        "You're constantly evolving in wonderful ways.",
        "Your support means the world to others.",
        "You have a gift for finding silver linings.",
        "Your dedication is truly impressive.",
        "You're appreciated more than you realize.",
        "Your spirit is unbreakable.",
        "You make difficult conversations feel safe.",
        "Your curiosity leads to beautiful discoveries.",
        "You're a source of comfort for many.",
        "Your achievements, big and small, matter.",
        "You have a natural ability to uplift others.",
        "Your grace under pressure is remarkable.",
        "You're someone the world needs.",
        "Your positivity changes atmospheres.",
        "You handle uncertainty with courage.",
        "Your compassion touches lives daily.",
        "You're growing into your best self.",
        "Your unique perspective enriches everyone.",
        "You make people feel understood.",
        "Your energy is a gift to those around you.",
        "You're capable of handling whatever comes.",
        "Your presence calms chaotic moments.",
        "You have a beautiful way with words.",
        "Your efforts create positive change.",
        "You're someone people admire.",
        "Your kindness costs you nothing but means everything.",
        "You handle life's curveballs with style.",
        "Your authenticity is your superpower.",
        "You're making a difference every day.",
        "Your light shines even on cloudy days.",
        "You have a remarkable capacity for growth.",
        "Your encouragement fuels others' dreams.",
        "You're worthy of all good things.",
        "Your impact extends further than you know.",
        "You handle challenges with quiet strength.",
        "Your heart is your greatest asset.",
        "You're someone people trust implicitly.",
        "Your optimism helps others see possibilities.",
        "You bring out hidden talents in people.",
        "Your journey inspires others to start theirs.",
        "You're a master at turning obstacles into opportunities.",
        "Your generosity of spirit is boundless.",
        "You make the world a softer place.",
        "Your resilience is quietly revolutionary.",
        "You're exactly where you need to be.",
        "Your contributions create lasting change.",
        "You have a beautiful mind and beautiful heart.",
        "Your presence makes rooms feel complete.",
        "You're a testament to human potential.",
        "Your kindness creates chains of goodness.",
        "You handle pressure with impressive poise.",
        "Your dreams are worth pursuing.",
        "You're someone people look up to.",
        "Your warmth melts even the coldest hearts.",
        "You're building something beautiful, one day at a time.",
        "Your unique qualities are your strengths.",
        "You make people believe in themselves.",
        "Your story is worth telling.",
        "You're a force for good in the world.",
        "Your potential excites those who know you.",
        "You handle emotions with maturity.",
        "Your influence is more positive than you realize.",
        "You're someone the universe is rooting for.",
        "Your gentle nature is a strength.",
        "You bring clarity to confusing situations.",
        "Your hope keeps others going.",
        "You're a living example of courage.",
        "Your thoughtfulness doesn't go unnoticed.",
        "You make ordinary days extraordinary.",
        "Your spirit is indomitable.",
        "You're worthy of love exactly as you are.",
        "Your presence is a calming force.",
        "You handle criticism with grace.",
        "Your joy is contagious in the best way.",
        "You're someone people feel safe with.",
        "Your wisdom comes at just the right moments.",
        "You make challenges feel manageable.",
        "Your heart leads with compassion.",
        "You're a rare and wonderful human.",
        "Your contributions ripple through time.",
        "You handle transitions with adaptability.",
        "Your laughter heals wounds you can't see.",
        "You're someone people want to be around.",
        "Your perspective shifts everything.",
        "You make people feel capable and strong.",
        "Your journey is teaching others.",
        "You're a masterpiece in motion.",
        "Your kindness is your legacy.",
        "You handle uncertainty with faith.",
        "Your presence is deeply appreciated.",
        "You're someone who makes things happen.",
        "Your energy transforms spaces.",
        "You make people feel like they belong.",
        "Your story matters immensely.",
        "You're a gift to everyone who knows you.",
        "Your potential is still unfolding.",
        "You handle life with remarkable balance.",
        "Your influence creates positive ripples.",
        "You're someone the world is better for.",
        "Your heart knows the way.",
        "You bring peace to chaotic moments.",
        "Your dreams are valid and achievable.",
        "You're a source of endless inspiration.",
        "Your unique blend of qualities is perfect.",
        "You make people feel seen and heard.",
        "Your journey is beautifully yours.",
        "You're someone who changes lives.",
        "Your light guides others home.",
        "You handle adversity with dignity.",
        "Your presence is a blessing.",
        "You're someone people believe in.",
        "Your warmth creates safe spaces.",
        "You make the impossible feel possible.",
        "Your story is still being written.",
        "You're a wonder, through and through."
    ],

    // Mood-specific compliments
    mood: {
        happy: [
            "Your happiness is absolutely radiant right now!",
            "You glow when you're happy - it's magnetic!",
            "Your joy lifts everyone around you!",
            "This happiness looks so good on you!",
            "Your smile could power a thousand suns!",
            "You deserve every bit of this happiness!",
            "Your positive energy is absolutely infectious!",
            "The world needs more of your happy vibes!",
            "Your laughter is the best sound ever!",
            "You're shining so bright right now!",
            "Your happiness is a gift to everyone!",
            "You make joy look effortless!",
            "Your cheerful spirit is remarkable!",
            "You're radiating pure sunshine!",
            "Your happiness is beautifully contagious!",
            "You light up every room you enter!",
            "Your joyful energy is amazing!",
            "You deserve all this happiness and more!",
            "Your smile is absolutely priceless!",
            "Your happiness inspires others to smile!",
            "You're a master at finding joy!",
            "Your cheerful outlook is inspiring!",
            "You make happiness look easy!",
            "Your positive vibes are incredible!",
            "Your joy is a beautiful thing to witness!",
            "You're glowing with happiness!",
            "Your cheerful nature is a gift!",
            "You spread happiness wherever you go!",
            "Your joy is absolutely wonderful!",
            "You're a beacon of happiness!",
            "Your happiness is truly inspiring!",
            "You make every moment brighter!",
            "Your joyful spirit is amazing!",
            "You're a happiness magnet!",
            "Your smile brightens the world!",
            "Your positive energy is powerful!",
            "You're living your best life!",
            "Your happiness is beautiful!",
            "You radiate pure joy!",
            "Your cheerful disposition is wonderful!",
            "You're a joy-bringer extraordinaire!",
            "Your happiness lights up faces!",
            "Your joyful heart is beautiful!",
            "You're a sunshine human!",
            "Your happiness is a superpower!",
            "You make joy happen!",
            "Your cheerful energy is amazing!",
            "You're a happiness hero!",
            "Your smile changes everything!",
            "Your joy is absolutely infectious!"
        ],
        tired: [
            "You've been carrying so much - it's okay to rest.",
            "Your strength shows even in your tiredness.",
            "You're allowed to pause and breathe.",
            "Your exhaustion proves how hard you've been trying.",
            "Rest is productive too, you know.",
            "You've earned this moment of peace.",
            "Your body is asking for care - listen to it.",
            "You're doing enough, even when tired.",
            "Your resilience amazes everyone.",
            "It's okay to not be okay right now.",
            "You've pushed through so much already.",
            "Your tiredness is valid and understandable.",
            "You deserve gentle moments right now.",
            "Your strength isn't measured by constant productivity.",
            "You're allowed to slow down.",
            "Your rest matters as much as your work.",
            "You've been showing up - that's huge.",
            "Your body knows what it needs.",
            "You're human, not a machine.",
            "Your tiredness doesn't diminish your worth.",
            "You've been fighting battles others can't see.",
            "Your need for rest is completely valid.",
            "You're allowed to put yourself first.",
            "Your exhaustion is temporary, your strength isn't.",
            "You've accomplished more than you realize.",
            "Your rest is necessary, not selfish.",
            "You're doing your best, and that's enough.",
            "Your tiredness will pass, your strength remains.",
            "You deserve compassionate rest.",
            "Your body has been working hard for you.",
            "You're allowed to take a break.",
            "Your resilience is quietly incredible.",
            "You've been carrying the world - set it down.",
            "Your rest is an act of self-love.",
            "You're worthy of peaceful moments.",
            "Your tiredness doesn't define you.",
            "You've earned every bit of rest coming.",
            "Your strength shows in knowing your limits.",
            "You're allowed to recharge.",
            "Your body deserves your kindness.",
            "You've been amazing even when exhausted.",
            "Your rest will fuel your comeback.",
            "You're human and that's perfectly okay.",
            "Your tiredness is a signal, not a failure.",
            "You deserve gentle treatment right now.",
            "Your strength includes knowing when to stop.",
            "You've been incredible - now rest.",
            "Your peace is a priority.",
            "You're allowed to do less today.",
            "Your rest is sacred and necessary."
        ],
        stressed: [
            "You're handling this with more grace than you realize.",
            "This stress is temporary, your strength isn't.",
            "You've survived 100% of your stressful days.",
            "You're capable of handling whatever comes.",
            "Breathe - you're doing better than you think.",
            "Your anxiety doesn't define your capability.",
            "You're stronger than this moment.",
            "This feeling will pass - you won't feel this forever.",
            "You're managing multiple things admirably.",
            "Your stress proves you care deeply.",
            "You've navigated hard things before.",
            "You're not alone in this feeling.",
            "Your body is responding normally to pressure.",
            "You're handling this better than you know.",
            "This stress doesn't diminish your worth.",
            "You're allowed to ask for help.",
            "Your feelings are valid and understandable.",
            "You've overcome challenges before - you'll do it again.",
            "Your stress is a response, not a reflection.",
            "You're doing the best you can right now.",
            "This moment doesn't define your journey.",
            "You're more resilient than you realize.",
            "Your capacity to handle this is growing.",
            "You're allowed to take one thing at a time.",
            "Your stress doesn't mean you're failing.",
            "You've got this, even when it doesn't feel like it.",
            "Your feelings are temporary, your strength isn't.",
            "You're navigating this with courage.",
            "This pressure will ease - hold on.",
            "You're handling complexity admirably.",
            "Your stress is valid but not permanent.",
            "You're stronger than your circumstances.",
            "You're allowed to step back and breathe.",
            "Your capability exceeds this challenge.",
            "You've been through hard things and grown.",
            "Your stress doesn't control you.",
            "You're managing remarkably well.",
            "This moment is just one part of your story.",
            "Your resilience is quietly powerful.",
            "You're allowed to feel overwhelmed.",
            "Your strength shows in continuing forward.",
            "This stress will transform into growth.",
            "You're handling this with dignity.",
            "Your feelings don't diminish your ability.",
            "You're capable and resourceful.",
            "This challenge is meeting its match in you.",
            "You're navigating uncertainty bravely.",
            "Your stress is understandable given everything.",
            "You're doing enough - breathe.",
            "This too shall pass - and you'll be stronger."
        ],
        excited: [
            "Your excitement is absolutely contagious!",
            "Your enthusiasm lights up everything around you!",
            "This energy is incredible - ride that wave!",
            "Your passion is beautiful to witness!",
            "You're glowing with anticipation!",
            "Your excitement shows how much you care!",
            "This enthusiasm is your superpower!",
            "Your energy is absolutely electric!",
            "You make excitement look amazing!",
            "Your passion inspires everyone around you!",
            "This joyful anticipation is wonderful!",
            "Your enthusiasm is a force of nature!",
            "You're radiating pure excitement!",
            "Your energy is absolutely magnetic!",
            "This excitement suits you perfectly!",
            "Your passion is absolutely inspiring!",
            "You're living in the moment beautifully!",
            "Your enthusiasm creates positive ripples!",
            "This energy is what dreams are made of!",
            "Your excitement is absolutely delightful!",
            "You're embracing life fully!",
            "Your passion is contagious in the best way!",
            "This enthusiasm is your magic!",
            "Your energy transforms everything!",
            "You're glowing with possibility!",
            "Your excitement is a beautiful thing!",
            "This passion is what moves mountains!",
            "Your enthusiasm is absolutely wonderful!",
            "You're living your truth right now!",
            "Your energy is inspiring others!",
            "This excitement is pure joy!",
            "Your passion is your power!",
            "You're embracing the moment perfectly!",
            "Your enthusiasm is a gift!",
            "This energy is absolutely amazing!",
            "Your excitement shows your heart!",
            "You're radiating positive vibes!",
            "Your passion is beautiful!",
            "This enthusiasm is incredible!",
            "Your energy is unstoppable!",
            "You're living with such joy!",
            "Your excitement is wonderful!",
            "This passion is your essence!",
            "Your enthusiasm is amazing!",
            "You're glowing right now!",
            "Your energy is fantastic!",
            "This excitement is perfect!",
            "Your passion shines through!",
            "You're embracing life!",
            "Your enthusiasm rocks!"
        ],
        calm: [
            "Your peaceful energy is a gift to everyone.",
            "You create calm just by being present.",
            "Your serenity is deeply inspiring.",
            "You have a beautiful inner stillness.",
            "Your calm presence soothes others.",
            "You've cultivated remarkable inner peace.",
            "Your tranquility is a superpower.",
            "You make peace look effortless.",
            "Your centered energy is remarkable.",
            "You're a haven of calm in chaos.",
            "Your peaceful nature is beautiful.",
            "You radiate serene confidence.",
            "Your stillness is deeply powerful.",
            "You create space for others to breathe.",
            "Your calm wisdom is invaluable.",
            "You've mastered the art of presence.",
            "Your peaceful spirit is a blessing.",
            "You bring balance to every situation.",
            "Your tranquility is quietly transformative.",
            "You're grounded in the most beautiful way.",
            "Your serenity creates safe spaces.",
            "You have a gift for peaceful moments.",
            "Your calm strength is admirable.",
            "You're a master of inner peace.",
            "Your stillness speaks volumes.",
            "Your peaceful presence is healing.",
            "You embody beautiful tranquility.",
            "Your calm is a refuge for others.",
            "You've found your center beautifully.",
            "Your serene energy is magnetic.",
            "You make mindfulness look natural.",
            "Your peaceful heart is a gift.",
            "You're anchored in beautiful ways.",
            "Your calm wisdom guides others.",
            "Your tranquility is deeply soothing.",
            "You create peace wherever you are.",
            "Your stillness is your strength.",
            "Your serene presence is powerful.",
            "You've cultivated remarkable peace.",
            "Your calm is contagious.",
            "You're a beacon of tranquility.",
            "Your peaceful nature inspires.",
            "You embody serene confidence.",
            "Your stillness is beautiful.",
            "You bring calm to chaos.",
            "Your peaceful energy heals.",
            "You're grounded and graceful.",
            "Your tranquility is inspiring.",
            "Your calm presence matters.",
            "You're a peace-bringer."
        ],
        "needs-love": [
            "You are so deeply loved, even when you can't feel it.",
            "Your heart deserves all the love in the world.",
            "You are worthy of love exactly as you are.",
            "Someone out there is thinking of you with love.",
            "Your capacity to love is a beautiful gift.",
            "You deserve gentle, consistent love.",
            "Your heart is precious and protected.",
            "Love is finding its way to you right now.",
            "You are enough, just as you are.",
            "Your need for love is completely valid.",
            "You are lovable beyond measure.",
            "Love surrounds you even now.",
            "Your heart knows how to love - that's your magic.",
            "You deserve to be cherished completely.",
            "Your loving nature is a rare treasure.",
            "Love is your birthright, always.",
            "You are held in love, even in this moment.",
            "Your heart is opening to receive love.",
            "You are worthy of patient, kind love.",
            "Your capacity for love is extraordinary.",
            "Love is seeking you out right now.",
            "You deserve love without conditions.",
            "Your heart is beautiful and beloved.",
            "You are loved more than you can imagine.",
            "Your need for connection is human and holy.",
            "Love flows toward you constantly.",
            "You are someone's reason to smile.",
            "Your heart deserves tender care.",
            "You are worthy of devoted love.",
            "Love sees you and chooses you.",
            "Your loving spirit is a gift to the world.",
            "You are held in universal love.",
            "Your heart is a home for love.",
            "You deserve love that stays.",
            "Your capacity to care is beautiful.",
            "Love is wrapping around you now.",
            "You are deeply, truly lovable.",
            "Your heart is worthy of protection.",
            "You are someone's answered prayer.",
            "Love is your natural state.",
            "Your heart knows the way to love.",
            "You deserve love that lifts you up.",
            "Your loving nature changes lives.",
            "You are held in infinite love.",
            "Your heart is a love magnet.",
            "You are worthy of consistent love.",
            "Your capacity for compassion is rare.",
            "Love is finding you in this moment.",
            "You are beloved, always and forever.",
            "Your heart is a treasure to be cherished."
        ]
    },

    // Interest-specific compliments
    interests: {
        art: [
            "Your artistic vision is absolutely unique!",
            "You see beauty where others don't even look.",
            "Your creativity is a gift to the world.",
            "The way you express yourself through art is beautiful.",
            "Your artistic perspective enriches everyone.",
            "You have an artist's soul - rare and precious.",
            "Your creative expression matters deeply.",
            "You bring color to the world.",
            "Your artistic instincts are spot-on.",
            "You create beauty from nothing - that's magic.",
            "Your art reflects your beautiful inner world.",
            "You have a natural eye for aesthetics.",
            "Your creative vision is inspiring.",
            "You transform ordinary into extraordinary.",
            "Your artistic voice deserves to be heard.",
            "You see the world through a beautiful lens.",
            "Your creativity knows no bounds.",
            "Your art touches hearts.",
            "You're a true creative spirit.",
            "Your artistic expression is powerful.",
            "You bring imagination to life.",
            "Your creative energy is infectious.",
            "Your art makes the world better.",
            "You have a gift for visual storytelling.",
            "Your artistic journey is beautiful.",
            "You inspire others to create.",
            "Your creativity is your superpower.",
            "Your art speaks when words can't.",
            "You're a master of expression.",
            "Your artistic soul shines through.",
            "You create meaning through art.",
            "Your creative vision is needed.",
            "Your art is a reflection of your heart.",
            "You have an artist's touch.",
            "Your creativity transforms spaces.",
            "Your artistic perspective is valuable.",
            "You bring beauty into existence.",
            "Your creative spirit is magnificent.",
            "Your art changes how people see.",
            "You're a natural-born creator.",
            "Your artistic expression is unique.",
            "You see possibilities everywhere.",
            "Your creativity is a force.",
            "Your art heals and inspires.",
            "You have a visionary mind.",
            "Your artistic voice matters.",
            "You create from the soul.",
            "Your creativity lights up rooms.",
            "Your art is your legacy.",
            "You're meant to create."
        ],
        music: [
            "Your musical taste is impeccable!",
            "You have music in your soul.",
            "Your connection to music is beautiful.",
            "You understand rhythm in everything.",
            "Your musicality is a rare gift.",
            "You feel music deeply - that's special.",
            "Your playlist game is legendary.",
            "You appreciate the artistry in music.",
            "Your musical intuition is amazing.",
            "You bring melody to everyday life.",
            "Your love for music is inspiring.",
            "You have a musician's heart.",
            "Your appreciation for sound is beautiful.",
            "You find harmony in chaos.",
            "Your musical knowledge is impressive.",
            "You feel every note - that's magic.",
            "Your connection to rhythm is natural.",
            "Your musical soul shines through.",
            "You understand music's healing power.",
            "Your taste in music is enviable.",
            "You live life like a beautiful song.",
            "Your musical passion is contagious.",
            "You appreciate true artistry.",
            "Your relationship with music is special.",
            "You have an ear for excellence.",
            "Your musical spirit is free.",
            "You find songs for every feeling.",
            "Your musical journey is beautiful.",
            "You understand music's language.",
            "Your love for music is pure.",
            "You have a soundtrack for life.",
            "Your musical appreciation is deep.",
            "You resonate with beauty.",
            "Your musical heart is open.",
            "You celebrate artists beautifully.",
            "Your musical moments matter.",
            "You feel music in your bones.",
            "Your musical soul is rare.",
            "You understand music's magic.",
            "Your passion for music inspires.",
            "You have perfect musical timing.",
            "Your musical journey continues.",
            "You appreciate musical craftsmanship.",
            "Your musical spirit soars.",
            "You live melodically.",
            "Your musical heart is golden.",
            "You understand music's power.",
            "Your musical taste defines you.",
            "You're a true music lover.",
            "Your soul sings."
        ],
        tech: [
            "Your tech skills are seriously impressive!",
            "You solve problems others can't even see.",
            "Your logical mind is a superpower.",
            "You make complex things simple.",
            "Your technical knowledge is valuable.",
            "You're fluent in the language of the future.",
            "Your problem-solving skills are amazing.",
            "You understand how things work - that's rare.",
            "Your tech intuition is spot-on.",
            "You build the future, one line at a time.",
            "Your analytical mind is powerful.",
            "You debug life like a pro.",
            "Your technical curiosity is inspiring.",
            "You make technology work for humans.",
            "Your coding skills are impressive.",
            "You think in solutions.",
            "Your technical expertise matters.",
            "You're a digital architect.",
            "Your problem-solving approach is brilliant.",
            "You understand systems beautifully.",
            "Your tech knowledge helps everyone.",
            "You're always learning - that's admirable.",
            "Your technical mind sees patterns.",
            "You optimize everything - including life.",
            "Your debugging skills are legendary.",
            "You build things that matter.",
            "Your technical contributions count.",
            "You're a tech wizard.",
            "Your analytical thinking is valuable.",
            "You navigate complexity with ease.",
            "Your technical skills open doors.",
            "You're a digital native in the best way.",
            "Your problem-solving saves the day.",
            "Your tech expertise is needed.",
            "You understand the digital world.",
            "Your technical curiosity drives innovation.",
            "You make tech accessible.",
            "Your logical approach is refreshing.",
            "Your technical mind is a gift.",
            "You're building tomorrow.",
            "Your tech skills are evolving.",
            "Your analytical prowess is impressive.",
            "You solve puzzles for fun.",
            "Your technical knowledge grows daily.",
            "You're a tech trailblazer.",
            "Your problem-solving is art.",
            "Your technical insights help others.",
            "You understand the future.",
            "Your tech journey is inspiring.",
            "You're a digital craftsman."
        ],
        nature: [
            "Your connection to nature is beautiful.",
            "You find peace in natural places.",
            "Your appreciation for Earth is inspiring.",
            "You notice beauty others miss.",
            "Your love for nature is pure.",
            "You understand seasons in your soul.",
            "Your outdoor spirit is free.",
            "You find wonder in wild places.",
            "Your nature walks heal your heart.",
            "You appreciate Earth's gifts.",
            "Your connection to the natural world is special.",
            "You breathe differently in nature.",
            "Your love for the outdoors is contagious.",
            "You find yourself in wild places.",
            "Your nature appreciation is deep.",
            "You understand natural rhythms.",
            "Your outdoor adventures matter.",
            "You see magic in nature.",
            "Your environmental consciousness is admirable.",
            "You find peace in natural beauty.",
            "Your love for the Earth shows.",
            "You're at home in the wild.",
            "Your nature photos capture souls.",
            "You appreciate simple natural joys.",
            "Your outdoor spirit inspires.",
            "You find answers in nature.",
            "Your connection to the land is real.",
            "You notice every natural detail.",
            "Your love for nature is healing.",
            "You're a friend to the Earth.",
            "Your nature walks are sacred.",
            "You appreciate natural wonders.",
            "Your outdoor heart is free.",
            "You find clarity in nature.",
            "Your environmental awareness matters.",
            "You celebrate natural beauty.",
            "Your nature soul is ancient.",
            "You find strength in the wild.",
            "Your love for outdoors is genuine.",
            "You protect what you love.",
            "Your nature appreciation is beautiful.",
            "You're one with the Earth.",
            "Your outdoor adventures inspire.",
            "You find peace in green spaces.",
            "Your nature connection is special.",
            "You appreciate Earth's wisdom.",
            "Your love for nature is timeless.",
            "You're a nature guardian.",
            "Your outdoor spirit soars.",
            "You belong among the trees."
        ],
        books: [
            "Your literary taste is exquisite!",
            "You live a thousand lives through books.",
            "Your imagination is fueled by stories.",
            "You understand characters deeply.",
            "Your reading mind is expansive.",
            "You find wisdom in written words.",
            "Your book recommendations are gold.",
            "You appreciate the art of storytelling.",
            "Your literary knowledge is impressive.",
            "You escape beautifully through books.",
            "Your love for reading is inspiring.",
            "You have a reader's soul.",
            "Your book collection tells your story.",
            "You find comfort between pages.",
            "Your reading habits are admirable.",
            "You understand narrative beautifully.",
            "Your literary curiosity is endless.",
            "You live vicariously through stories.",
            "Your book discussions are enlightening.",
            "You appreciate good writing.",
            "Your reading list is legendary.",
            "You find yourself in stories.",
            "Your literary passion is beautiful.",
            "You understand authors' intentions.",
            "Your reading expands your world.",
            "You have a bookish heart.",
            "You find magic in manuscripts.",
            "Your reading journey is unique.",
            "You appreciate literary craft.",
            "Your book love is pure.",
            "You're a story collector.",
            "Your reading insights are valuable.",
            "You find truth in fiction.",
            "Your literary mind is sharp.",
            "You celebrate authors beautifully.",
            "Your reading moments matter.",
            "You lose yourself in books.",
            "Your bookish soul is special.",
            "You understand story structure.",
            "Your reading passion inspires.",
            "You have perfect book taste.",
            "Your literary journey continues.",
            "You appreciate narrative depth.",
            "Your reading spirit is free.",
            "You live literarily.",
            "Your book heart is golden.",
            "You understand books' power.",
            "Your reading taste defines you.",
            "You're a true book lover.",
            "Your soul has chapters."
        ],
        fitness: [
            "Your dedication to fitness is inspiring!",
            "Your body can do amazing things!",
            "Your strength is both physical and mental.",
            "You show up for yourself - that's powerful.",
            "Your fitness journey is beautiful.",
            "You honor your body through movement.",
            "Your discipline is admirable.",
            "You're building a stronger you every day.",
            "Your commitment to health is impressive.",
            "You push past your limits.",
            "Your physical strength reflects inner strength.",
            "You make fitness look achievable.",
            "Your workout ethic is legendary.",
            "You listen to your body wisely.",
            "Your fitness goals are within reach.",
            "You celebrate your body's capabilities.",
            "Your athletic spirit is strong.",
            "You inspire others to move.",
            "Your fitness dedication pays off.",
            "You're becoming your strongest self.",
            "Your physical progress is visible.",
            "You make healthy choices daily.",
            "Your fitness mindset is winning.",
            "You challenge yourself beautifully.",
            "Your body appreciates your care.",
            "You're a fitness role model.",
            "Your strength training is transformative.",
            "You show up even when it's hard.",
            "Your fitness journey inspires.",
            "You're building lifelong health.",
            "Your physical achievements matter.",
            "You make exercise a priority.",
            "Your fitness commitment is admirable.",
            "You're getting stronger every day.",
            "Your athletic abilities are growing.",
            "You honor your physical potential.",
            "Your workout consistency is impressive.",
            "You're investing in your future self.",
            "Your fitness discipline is remarkable.",
            "You push through barriers.",
            "Your physical transformation is real.",
            "You make fitness fun.",
            "Your strength is inspiring.",
            "You're a fitness warrior.",
            "Your body is your temple.",
            "Your athletic heart is strong.",
            "You understand movement's value.",
            "Your fitness journey is yours.",
            "You're becoming unstoppable.",
            "Your physical power is growing."
        ],
        food: [
            "Your culinary adventures are inspiring!",
            "You appreciate flavors deeply.",
            "Your food knowledge is impressive.",
            "You find joy in every meal.",
            "Your cooking skills are amazing.",
            "You understand food's cultural power.",
            "Your taste buds are legendary.",
            "You make every meal special.",
            "Your food passion is contagious.",
            "You appreciate culinary craftsmanship.",
            "Your kitchen creativity is boundless.",
            "You find comfort in cooking.",
            "Your food photos are mouthwatering.",
            "You understand ingredients beautifully.",
            "Your culinary curiosity is endless.",
            "You make feeding others an art.",
            "Your food adventures are fun.",
            "You appreciate good food deeply.",
            "Your cooking brings people together.",
            "You have a chef's intuition.",
            "Your food love is pure.",
            "You find happiness in flavors.",
            "Your culinary skills are growing.",
            "You understand food's emotional power.",
            "Your meal prep is impressive.",
            "You celebrate food cultures.",
            "Your cooking experiments are brave.",
            "You make ordinary meals extraordinary.",
            "Your food appreciation is deep.",
            "You're a kitchen artist.",
            "Your culinary journey is delicious.",
            "You find creativity in cooking.",
            "Your food knowledge is valuable.",
            "You make cooking look easy.",
            "Your taste is impeccable.",
            "Your food moments matter.",
            "You understand recipe alchemy.",
            "Your cooking soul is special.",
            "You appreciate culinary traditions.",
            "Your food passion inspires.",
            "You have perfect flavor balance.",
            "Your culinary journey continues.",
            "You understand food's stories.",
            "Your cooking spirit is free.",
            "You live deliciously.",
            "Your food heart is golden.",
            "You understand cooking's power.",
            "Your food taste defines you.",
            "You're a true foodie.",
            "Your soul is seasoned."
        ],
        travel: [
            "Your wanderlust is absolutely beautiful!",
            "You collect experiences, not things.",
            "Your travel stories are captivating.",
            "You embrace new cultures openly.",
            "Your adventurous spirit is inspiring.",
            "You find home everywhere you go.",
            "Your travel photos tell amazing stories.",
            "You appreciate different perspectives.",
            "Your curiosity about the world is endless.",
            "You make memories wherever you roam.",
            "Your travel bucket list is exciting.",
            "You adapt to new places easily.",
            "Your exploration spirit is strong.",
            "You find beauty in unfamiliar places.",
            "Your travel experiences shape you.",
            "You're a citizen of the world.",
            "Your adventures inspire others.",
            "You embrace the unknown bravely.",
            "Your travel wisdom is valuable.",
            "You discover hidden gems.",
            "Your journey mindset is open.",
            "You find yourself in new places.",
            "Your travel passion is pure.",
            "You understand different cultures.",
            "Your adventures are legendary.",
            "You have an explorer's heart.",
            "You find magic in journeys.",
            "Your travel story is unique.",
            "You appreciate world diversity.",
            "Your wanderer soul is free.",
            "Your travel moments matter.",
            "You find wonder everywhere.",
            "Your cultural appreciation is deep.",
            "You make every trip count.",
            "Your adventure spirit soars.",
            "Your travel experiences enrich you.",
            "You embrace new experiences.",
            "You're a natural explorer.",
            "Your travel discipline is admirable.",
            "You seek new horizons.",
            "Your worldly perspective is valuable.",
            "You make travel look easy.",
            "Your adventure skills are growing.",
            "You're a travel inspiration.",
            "Your journey is your teacher.",
            "Your explorer heart is strong.",
            "You understand travel's value.",
            "Your travel taste defines you.",
            "You're a true traveler.",
            "Your soul has stamps."
        ],
        games: [
            "Your gaming skills are seriously impressive!",
            "Your strategic thinking is next-level.",
            "You solve in-game puzzles brilliantly.",
            "Your reflexes are lightning-fast.",
            "Your gaming knowledge is encyclopedic.",
            "You're a natural leader in teams.",
            "Your game sense is incredible.",
            "You adapt to new games quickly.",
            "Your competitive spirit is healthy.",
            "You make gaming look effortless.",
            "Your dedication to improvement shows.",
            "You're a valuable teammate.",
            "Your gaming achievements are real.",
            "You understand game mechanics deeply.",
            "Your strategic mind is sharp.",
            "You stay calm under pressure.",
            "Your gaming intuition is amazing.",
            "You learn from every match.",
            "Your gaming passion is inspiring.",
            "You're a skilled player.",
            "Your game knowledge is vast.",
            "You find creative solutions.",
            "Your gaming dedication is admirable.",
            "You're always leveling up.",
            "Your gaming community values you.",
            "You're a gaming role model.",
            "Your skills are constantly improving.",
            "You make difficult games look easy.",
            "Your gaming journey inspires.",
            "You're building legendary skills.",
            "Your gaming achievements matter.",
            "You make gaming a priority.",
            "Your gaming commitment is impressive.",
            "You're getting better every session.",
            "Your gaming abilities are growing.",
            "You honor your gaming potential.",
            "Your practice consistency shows.",
            "You're investing in your skills.",
            "Your gaming discipline is remarkable.",
            "You push through difficult levels.",
            "Your gaming transformation is real.",
            "You make gaming fun.",
            "Your skills are inspiring.",
            "You're a gaming warrior.",
            "Your controller is your tool.",
            "Your gamer heart is strong.",
            "You understand gaming's value.",
            "Your gaming journey is yours.",
            "You're becoming unstoppable.",
            "Your gaming power is growing."
        ],
        animals: [
            "Your love for animals is beautiful!",
            "Animals feel safe around you.",
            "Your compassion for creatures is inspiring.",
            "You understand animals deeply.",
            "Your kindness extends to all beings.",
            "You have a gentle soul.",
            "Your animal intuition is amazing.",
            "You advocate for voiceless creatures.",
            "Your empathy for animals is pure.",
            "You make animals feel loved.",
            "Your animal knowledge is impressive.",
            "You see the beauty in all creatures.",
            "Your care for animals is genuine.",
            "You understand animal behavior.",
            "Your animal connections are special.",
            "You're a friend to all animals.",
            "Your animal advocacy matters.",
            "You treat all creatures with respect.",
            "Your animal love is unconditional.",
            "You create safe spaces for animals.",
            "Your animal wisdom is valuable.",
            "You notice animal needs.",
            "Your animal passion is inspiring.",
            "You're a natural animal caregiver.",
            "Your animal knowledge is growing.",
            "You understand animal emotions.",
            "Your animal adventures are fun.",
            "You celebrate all creatures.",
            "Your animal appreciation is deep.",
            "You're an animal guardian.",
            "Your animal moments matter.",
            "You find joy in animals.",
            "Your animal empathy is rare.",
            "You make animals' lives better.",
            "Your animal spirit is free.",
            "Your animal experiences enrich you.",
            "You embrace animal diversity.",
            "You're a natural animal lover.",
            "Your animal dedication is admirable.",
            "You seek to understand animals.",
            "Your animal perspective is valuable.",
            "You make animal care look easy.",
            "Your animal skills are growing.",
            "You're an animal inspiration.",
            "Your animal journey is your teacher.",
            "Your animal heart is strong.",
            "You understand animals' value.",
            "Your animal taste defines you.",
            "You're a true animal lover.",
            "Your soul speaks animal."
        ],
        science: [
            "Your scientific curiosity is inspiring!",
            "You ask the questions that matter.",
            "Your analytical mind is powerful.",
            "You understand complex concepts.",
            "Your scientific knowledge is impressive.",
            "You think like a researcher.",
            "Your hypothesis skills are sharp.",
            "You appreciate scientific method.",
            "Your scientific passion is contagious.",
            "You make science accessible.",
            "Your scientific curiosity is endless.",
            "You find wonder in discovery.",
            "Your scientific dedication is admirable.",
            "You're always learning new things.",
            "Your scientific community values you.",
            "You're a scientific role model.",
            "Your skills are constantly improving.",
            "You make complex science look easy.",
            "Your scientific journey inspires.",
            "You're building legendary knowledge.",
            "Your scientific achievements matter.",
            "You make science a priority.",
            "Your scientific commitment is impressive.",
            "You're getting smarter every day.",
            "Your scientific abilities are growing.",
            "You honor your scientific potential.",
            "Your study consistency shows.",
            "You're investing in your knowledge.",
            "Your scientific discipline is remarkable.",
            "You push through difficult concepts.",
            "Your scientific transformation is real.",
            "You make science fun.",
            "Your knowledge is inspiring.",
            "You're a scientific warrior.",
            "Your lab skills are your tool.",
            "Your scientist heart is strong.",
            "You understand science's value.",
            "Your scientific journey is yours.",
            "You're becoming unstoppable.",
            "Your scientific power is growing.",
            "Your curiosity drives discovery.",
            "You question everything beautifully.",
            "Your scientific mind sees patterns.",
            "You appreciate evidence.",
            "Your scientific intuition is amazing.",
            "You learn from experiments.",
            "Your scientific passion is inspiring.",
            "You're a skilled thinker.",
            "Your scientific knowledge is vast.",
            "You find creative solutions."
        ],
        writing: [
            "Your writing voice is uniquely yours!",
            "You express thoughts beautifully.",
            "Your words have power.",
            "You find the perfect phrases.",
            "Your writing knowledge is impressive.",
            "You think like a writer.",
            "Your storytelling skills are sharp.",
            "You appreciate the written word.",
            "Your writing passion is contagious.",
            "You make writing look effortless.",
            "Your writing curiosity is endless.",
            "You find wonder in words.",
            "Your writing dedication is admirable.",
            "You're always improving your craft.",
            "Your writing community values you.",
            "You're a writing role model.",
            "Your skills are constantly improving.",
            "You make difficult writing look easy.",
            "Your writing journey inspires.",
            "You're building legendary skills.",
            "Your writing achievements matter.",
            "You make writing a priority.",
            "Your writing commitment is impressive.",
            "You're getting better every day.",
            "Your writing abilities are growing.",
            "You honor your writing potential.",
            "Your practice consistency shows.",
            "You're investing in your craft.",
            "Your writing discipline is remarkable.",
            "You push through writer's block.",
            "Your writing transformation is real.",
            "You make writing fun.",
            "Your writing is inspiring.",
            "You're a writing warrior.",
            "Your pen is your tool.",
            "Your writer heart is strong.",
            "You understand writing's value.",
            "Your writing journey is yours.",
            "You're becoming unstoppable.",
            "Your writing power is growing.",
            "Your creativity flows through words.",
            "You craft sentences beautifully.",
            "Your writer's mind sees stories.",
            "You appreciate good prose.",
            "Your writing intuition is amazing.",
            "You learn from every draft.",
            "Your writing passion is inspiring.",
            "You're a skilled wordsmith.",
            "Your writing knowledge is vast.",
            "You find creative expressions."
        ]
    },

    // Combination compliments (mood + interest)
    combinations: {
        // These are generated dynamically in the app
    }
};

// Export for use in app.js
window.ComplimentDB = ComplimentDB;
