import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import logger from '../utils/logger.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

class ExportService {
  constructor() {
    this.exportDir = path.join(__dirname, '../../exports');
  }
  
  /**
   * Export world to WebGL format
   */
  async exportToWebGL(worldData, options = {}) {
    try {
      const exportId = `webgl-${worldData._id}-${Date.now()}`;
      const exportPath = path.join(this.exportDir, exportId);
      
      await fs.mkdir(exportPath, { recursive: true });
      
      // Generate Three.js compatible scene
      const sceneData = {
        metadata: {
          version: '1.0.0',
          type: 'Scene',
          generator: 'WorldForge AI WebGL Exporter'
        },
        world: {
          name: worldData.name,
          dimensions: worldData.dimensions,
          size: options.size || { width: 1000, height: 1000 }
        },
        terrain: this._convertTerrainToThreeJS(worldData.terrain),
        objects: this._convertAssetsToThreeJS(worldData.assets),
        lighting: this._generateLighting(worldData),
        skybox: this._generateSkybox(worldData),
        physics: this._generatePhysicsConfig(worldData)
      };
      
      // Write scene JSON
      await fs.writeFile(
        path.join(exportPath, 'scene.json'),
        JSON.stringify(sceneData, null, 2)
      );
      
      // Generate HTML template
      const htmlTemplate = this._generateWebGLTemplate(worldData);
      await fs.writeFile(
        path.join(exportPath, 'index.html'),
        htmlTemplate
      );
      
      // Generate JavaScript loader
      const jsCode = this._generateWebGLLoader(worldData);
      await fs.writeFile(
        path.join(exportPath, 'main.js'),
        jsCode
      );
      
      // Copy assets
      await this._copyAssetsForExport(worldData.assets, exportPath);
      
      return {
        success: true,
        exportId,
        path: exportPath,
        format: 'webgl',
        files: ['scene.json', 'index.html', 'main.js', 'assets/']
      };
    } catch (error) {
      logger.error('WebGL export failed:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }
  
  /**
   * Export world to Unity format
   */
  async exportToUnity(worldData, options = {}) {
    try {
      const exportId = `unity-${worldData._id}-${Date.now()}`;
      const exportPath = path.join(this.exportDir, exportId);
      
      await fs.mkdir(exportPath, { recursive: true });
      
      // Create Unity package structure
      const unityPackage = {
        name: worldData.name.replace(/\s+/g, '_'),
        version: '1.0.0',
        unity: '2022.3',
        scenes: [],
        prefabs: [],
        materials: [],
        scripts: []
      };
      
      // Generate scene file
      const unityScene = {
        name: worldData.name,
        objects: this._convertToUnityObjects(worldData),
        lighting: this._convertToUnityLighting(worldData),
        terrain: this._convertToUnityTerrain(worldData.terrain)
      };
      
      await fs.writeFile(
        path.join(exportPath, 'Scene.unity'),
        this._generateUnitySceneFile(unityScene)
      );
      
      // Generate C# scripts for game logic
      const scripts = this._generateUnityScripts(worldData.rules, worldData.quests);
      for (const [name, code] of Object.entries(scripts)) {
        await fs.writeFile(
          path.join(exportPath, 'Scripts', name),
          code
        );
      }
      
      // Generate asset bundles manifest
      await fs.writeFile(
        path.join(exportPath, 'AssetBundleManifest.json'),
        JSON.stringify(this._generateAssetBundleManifest(worldData.assets), null, 2)
      );
      
      // Create README with import instructions
      const readme = `# ${worldData.name} - Unity Export

## Import Instructions

1. Copy all files to your Unity project's Assets folder
2. Open the Scene.unity file
3. Install required packages (see Packages folder)
4. Build and run!

## Generated Scripts

${Object.keys(scripts).map(s => `- ${s}`).join('\n')}

## Notes

- Generated by WorldForge AI
- Unity version: 2022.3+
- Render pipeline: Universal (URP)
`;
      
      await fs.writeFile(
        path.join(exportPath, 'README.md'),
        readme
      );
      
      return {
        success: true,
        exportId,
        path: exportPath,
        format: 'unity',
        files: ['Scene.unity', 'Scripts/', 'AssetBundleManifest.json', 'README.md']
      };
    } catch (error) {
      logger.error('Unity export failed:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }
  
  /**
   * Export world to Godot format
   */
  async exportToGodot(worldData, options = {}) {
    try {
      const exportId = `godot-${worldData._id}-${Date.now()}`;
      const exportPath = path.join(this.exportDir, exportId);
      
      await fs.mkdir(exportPath, { recursive: true });
      
      // Create Godot project structure
      const projectConfig = this._generateGodotProjectConfig(worldData);
      await fs.writeFile(
        path.join(exportPath, 'project.godot'),
        projectConfig
      );
      
      // Generate main scene
      const mainScene = this._generateGodotMainScene(worldData);
      await fs.writeFile(
        path.join(exportPath, 'Main.tscn'),
        mainScene
      );
      
      // Generate GDScript files
      const scripts = this._generateGodotScripts(worldData.rules, worldData.quests);
      for (const [name, code] of Object.entries(scripts)) {
        await fs.writeFile(
          path.join(exportPath, 'Scripts', name),
          code
        );
      }
      
      // Generate resource files
      const resources = this._generateGodotResources(worldData);
      for (const [name, content] of Object.entries(resources)) {
        await fs.writeFile(
          path.join(exportPath, 'Resources', name),
          content
        );
      }
      
      // Create README
      const readme = `# ${worldData.name} - Godot Export

## Requirements

- Godot Engine 4.0+
- No additional plugins required

## Import Instructions

1. Open Godot Engine
2. Click "Import" and select the project.godot file
3. Open Main.tscn scene
4. Run the project!

## Generated Scripts

${Object.keys(scripts).map(s => `- ${s}`).join('\n')}

---
Generated by WorldForge AI
`;
      
      await fs.writeFile(
        path.join(exportPath, 'README.md'),
        readme
      );
      
      return {
        success: true,
        exportId,
        path: exportPath,
        format: 'godot',
        files: ['project.godot', 'Main.tscn', 'Scripts/', 'Resources/', 'README.md']
      };
    } catch (error) {
      logger.error('Godot export failed:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }
  
  /**
   * Export to glTF/GLB format (universal 3D)
   */
  async exportToGLTF(worldData, options = {}) {
    try {
      const exportId = `gltf-${worldData._id}-${Date.now()}`;
      const exportPath = path.join(this.exportDir, exportId);
      
      await fs.mkdir(exportPath, { recursive: true });
      
      // Generate glTF scene
      const gltfScene = {
        asset: {
          version: '2.0',
          generator: 'WorldForge AI glTF Exporter'
        },
        scene: 0,
        scenes: [{
          nodes: this._convertToGLTFNodes(worldData)
        }],
        nodes: this._generateGLTFNodes(worldData),
        meshes: this._generateGLTFMeshes(worldData.assets),
        materials: this._generateGLTFMaterials(worldData.assets),
        textures: this._generateGLTFTextures(worldData.assets),
        images: this._generateGLTFImages(worldData.assets)
      };
      
      await fs.writeFile(
        path.join(exportPath, 'scene.gltf'),
        JSON.stringify(gltfScene, null, 2)
      );
      
      return {
        success: true,
        exportId,
        path: exportPath,
        format: 'gltf',
        files: ['scene.gltf']
      };
    } catch (error) {
      logger.error('glTF export failed:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }
  
  // Helper methods (implementation details)
  _convertTerrainToThreeJS(terrain) {
    return {
      type: 'HeightmapTerrain',
      data: terrain?.heightmap || [],
      biomes: terrain?.biomes || [],
      resolution: terrain?.resolution || 256
    };
  }
  
  _convertAssetsToThreeJS(assets) {
    return (assets || []).map(asset => ({
      id: asset._id,
      type: asset.type,
      position: asset.position || { x: 0, y: 0, z: 0 },
      rotation: asset.rotation || { x: 0, y: 0, z: 0 },
      scale: asset.scale || { x: 1, y: 1, z: 1 },
      geometry: asset.geometry || 'box',
      material: asset.material || 'standard'
    }));
  }
  
  _generateLighting(worldData) {
    return {
      ambient: { color: 0x404040, intensity: 0.5 },
      directional: {
        color: 0xffffff,
        intensity: 1,
        position: { x: 50, y: 100, z: 50 }
      },
      hemispheric: {
        skyColor: 0x87ceeb,
        groundColor: 0x404040,
        intensity: 0.6
      }
    };
  }
  
  _generateSkybox(worldData) {
    return {
      type: 'procedural',
      parameters: {
        turbidity: 10,
        rayleigh: 2,
        mieCoefficient: 0.005,
        mieDirectionalG: 0.8
      }
    };
  }
  
  _generatePhysicsConfig(worldData) {
    return {
      enabled: true,
      gravity: { x: 0, y: -9.81, z: 0 },
      defaultMaterial: {
        friction: 0.5,
        restitution: 0.3
      }
    };
  }
  
  _generateWebGLTemplate(worldData) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${worldData.name} - WorldForge AI</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { overflow: hidden; background: #000; }
    canvas { display: block; }
    #loading {
      position: fixed; top: 0; left: 0; width: 100%; height: 100%;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      display: flex; align-items: center; justify-content: center;
      color: white; font-family: Arial, sans-serif; z-index: 9999;
    }
    #loading.hidden { display: none; }
  </style>
</head>
<body>
  <div id="loading">Loading ${worldData.name}...</div>
  <script type="module" src="main.js"></script>
</body>
</html>`;
  }
  
  _generateWebGLLoader(worldData) {
    return `import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

// WorldForge AI WebGL Runtime
class WorldRuntime {
  constructor() {
    this.scene = new THREE.Scene();
    this.camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    this.renderer = new THREE.WebGLRenderer({ antialias: true });
    this.controls = null;
    this.objects = [];
    
    this.init();
  }
  
  init() {
    this.renderer.setSize(window.innerWidth, window.innerHeight);
    this.renderer.setPixelRatio(window.devicePixelRatio);
    document.body.appendChild(this.renderer.domElement);
    
    this.camera.position.set(0, 10, 20);
    this.controls = new OrbitControls(this.camera, this.renderer.domElement);
    
    this.loadScene();
    this.animate();
    
    window.addEventListener('resize', () => this.onWindowResize());
    
    document.getElementById('loading').classList.add('hidden');
  }
  
  async loadScene() {
    const response = await fetch('scene.json');
    const data = await response.json();
    
    // Load terrain, objects, lighting from data
    this.loadTerrain(data.terrain);
    this.loadObjects(data.objects);
    this.loadLighting(data.lighting);
  }
  
  loadTerrain(terrainData) {
    // Implement terrain loading
    console.log('Loading terrain:', terrainData);
  }
  
  loadObjects(objects) {
    objects.forEach(obj => {
      const geometry = new THREE.BoxGeometry(1, 1, 1);
      const material = new THREE.MeshStandardMaterial({ color: 0x00ff00 });
      const mesh = new THREE.Mesh(geometry, material);
      mesh.position.set(obj.position.x, obj.position.y, obj.position.z);
      this.scene.add(mesh);
      this.objects.push(mesh);
    });
  }
  
  loadLighting(lightingData) {
    const ambientLight = new THREE.AmbientLight(
      lightingData.ambient.color,
      lightingData.ambient.intensity
    );
    this.scene.add(ambientLight);
    
    const directionalLight = new THREE.DirectionalLight(
      lightingData.directional.color,
      lightingData.directional.intensity
    );
    directionalLight.position.set(
      lightingData.directional.position.x,
      lightingData.directional.position.y,
      lightingData.directional.position.z
    );
    this.scene.add(directionalLight);
  }
  
  onWindowResize() {
    this.camera.aspect = window.innerWidth / window.innerHeight;
    this.camera.updateProjectionMatrix();
    this.renderer.setSize(window.innerWidth, window.innerHeight);
  }
  
  animate() {
    requestAnimationFrame(() => this.animate());
    this.controls.update();
    this.renderer.render(this.scene, this.camera);
  }
}

// Start the world
new WorldRuntime();`;
  }
  
  _generateGodotProjectConfig(worldData) {
    return `; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

config/name="${worldData.name}"
config/description="Generated by WorldForge AI"
run/main_scene="res://Main.tscn"
config/features=PackedStringArray("4.0", "Forward Plus")

[rendering]

anti_aliasing/quality/msaa_3d=2
anti_aliasing/quality/screen_space_aa=1`;
  }
  
  _generateGodotMainScene(worldData) {
    return `[gd_scene load_steps=3 format=3 uid="uid://${worldData._id}"]

[ext_resource type="Script" path="res://Scripts/WorldController.gd" id="1_world"]

[node name="World" type="Node3D"]
script = ExtResource("1_world")

[node name="Terrain" type="Terrain3D" parent="."]

[node name="Player" type="CharacterBody3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1.5, 0)

[node name="Camera" type="Camera3D" parent="Player"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.5, 0)

[node name="DirectionalLight" type="DirectionalLight3D" parent="."]
transform = Transform3D(0.866, -0.433, 0.25, 0, 0.5, 0.866, -0.5, -0.75, 0.433, 10, 20, 10)`;
  }
  
  _generateGodotScripts(rules, quests) {
    const worldController = `extends Node3D

# WorldForge AI - Generated World Controller

@export var world_name: String = "${rules?.name || 'World'}"
@export var spawn_point: Vector3 = Vector3.ZERO

var players: Array = []
var npcs: Array = []
var active_quests: Array = []

func _ready():
	print("Welcome to ", world_name)
	setup_world()
	load_quests()

func setup_world():
	# Initialize world systems
	pass

func load_quests():
	# Load quest data
	pass

func _process(delta):
	# Update game logic
	pass`;

    const playerController = `extends CharacterBody3D

# Player Controller - Generated by WorldForge AI

@export var speed: float = 5.0
@export var jump_velocity: float = 4.5

var gravity = ProjectSettings.get_setting("physics/3d/default_gravity")

func _physics_process(delta):
	# Add gravity
	if not is_on_floor():
		velocity.y -= gravity * delta
	
	# Handle jump
	if Input.is_action_just_pressed("ui_accept") and is_on_floor():
		velocity.y = jump_velocity
	
	# Get input direction
	var input_dir = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
	var direction = (transform.basis * Vector3(input_dir.x, 0, input_dir.y)).normalized()
	
	if direction:
		velocity.x = direction.x * speed
		velocity.z = direction.z * speed
	else:
		velocity.x = move_toward(velocity.x, 0, speed)
		velocity.z = move_toward(velocity.z, 0, speed)
	
	move_and_slide()`;

    return {
      'WorldController.gd': worldController,
      'PlayerController.gd': playerController
    };
  }
  
  _generateUnityScripts(rules, quests) {
    const worldManager = `using UnityEngine;
using System.Collections.Generic;

// WorldForge AI - Generated World Manager

public class WorldManager : MonoBehaviour
{
    public string worldName = "${rules?.name || 'World'}";
    public Transform spawnPoint;
    
    public static WorldManager Instance { get; private set; }
    
    private List<PlayerController> players = new List<PlayerController>();
    private List<NPCController> npcs = new List<NPCController>();
    private List<Quest> activeQuests = new List<Quest>();
    
    void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
        }
    }
    
    void Start()
    {
        Debug.Log("Welcome to " + worldName);
        InitializeWorld();
    }
    
    void InitializeWorld()
    {
        // Initialize world systems
    }
    
    public void AddPlayer(PlayerController player)
    {
        players.Add(player);
    }
    
    public void RemovePlayer(PlayerController player)
    {
        players.Remove(player);
    }
}`;

    const playerController = `using UnityEngine;

// Player Controller - Generated by WorldForge AI

[RequireComponent(typeof(CharacterController))]
public class PlayerController : MonoBehaviour
{
    [Header("Movement")]
    public float walkSpeed = 5f;
    public float runSpeed = 10f;
    public float jumpSpeed = 5f;
    public float gravity = 20f;
    
    [Header("Camera")]
    public Transform cameraTransform;
    public float mouseSensitivity = 2f;
    
    private CharacterController characterController;
    private Vector3 moveDirection = Vector3.zero;
    private float rotationX = 0;
    
    void Start()
    {
        characterController = GetComponent<CharacterController>();
        WorldManager.Instance?.AddPlayer(this);
    }
    
    void Update()
    {
        HandleMovement();
        HandleCamera();
    }
    
    void HandleMovement()
    {
        if (characterController.isGrounded)
        {
            moveDirection = new Vector3(
                Input.GetAxis("Horizontal"),
                0,
                Input.GetAxis("Vertical")
            );
            moveDirection = transform.TransformDirection(moveDirection);
            moveDirection *= walkSpeed;
            
            if (Input.GetButton("Jump"))
                moveDirection.y = jumpSpeed;
        }
        
        moveDirection.y -= gravity * Time.deltaTime;
        characterController.Move(moveDirection * Time.deltaTime);
    }
    
    void HandleCamera()
    {
        rotationX += -Input.GetAxis("Mouse Y") * mouseSensitivity;
        rotationX = Mathf.Clamp(rotationX, -90, 90);
        cameraTransform.localRotation = Quaternion.Euler(rotationX, 0, 0);
        transform.rotation *= Quaternion.Euler(0, Input.GetAxis("Mouse X") * mouseSensitivity, 0);
    }
    
    void OnDestroy()
    {
        WorldManager.Instance?.RemovePlayer(this);
    }
}`;

    return {
      'WorldManager.cs': worldManager,
      'PlayerController.cs': playerController
    };
  }
  
  _copyAssetsForExport(assets, exportPath) {
    // Implementation for copying asset files
    return Promise.resolve();
  }
  
  _convertToUnityObjects(worldData) {
    return [];
  }
  
  _convertToUnityLighting(worldData) {
    return {};
  }
  
  _convertToUnityTerrain(terrain) {
    return {};
  }
  
  _generateUnitySceneFile(scene) {
    return `# Unity Scene File
# Generated by WorldForge AI

%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!29 &1
OcclusionCullingSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_OcclusionBakeSettings:
    smallestOccluder: 5
    smallestHole: 0.25
    backfaceThreshold: 100
  m_SceneGUID: 00000000000000000000000000000000
  m_OcclusionCullingData: {fileID: 0}
--- !u!104 &2
RenderSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 9
  m_Fog: 0
  m_FogColor: {r: 0.5, g: 0.5, b: 0.5, a: 1}
  m_FogMode: 3
  m_FogDensity: 0.01
  m_CustomFog: 0
  m_AmbientSkyColor: {r: 0.212, g: 0.227, b: 0.259, a: 1}
  m_AmbientEquatorColor: {r: 0.114, g: 0.125, b: 0.133, a: 1}
  m_AmbientGroundColor: {r: 0.047, g: 0.043, b: 0.035, a: 1}
  m_AmbientIntensity: 1
  m_AmbientMode: 3
  m_SubtractiveShadowColor: {r: 0.42, g: 0.478, b: 0.627, a: 1}
  m_SkyboxMaterial: {fileID: 0}
  m_HaloStrength: 0.5
  m_FlareStrength: 1
  m_FlareFadeSpeed: 3
  m_HaloTexture: {fileID: 0}
  m_SpotCookie: {fileID: 10001, guid: 0000000000000000e000000000000000, type: 0}
  m_DefaultReflectionMode: 0
  m_DefaultReflectionResolution: 128
  m_ReflectionBounces: 1
  m_ReflectionIntensity: 1
  m_CustomReflection: {fileID: 0}
  m_Sun: {fileID: 0}
  m_IndirectSpecularColor: {r: 0, g: 0, b: 0, a: 1}
  m_UseRadianceAmbientProbe: 0`;
  }
  
  _generateAssetBundleManifest(assets) {
    return {
      assets: assets.map(a => ({
        id: a._id,
        name: a.name,
        type: a.type,
        bundle: `${a.type}_bundle`
      }))
    };
  }
  
  _generateGLTFNodes(worldData) {
    return [];
  }
  
  _generateGLTFMeshes(assets) {
    return [];
  }
  
  _generateGLTFMaterials(assets) {
    return [];
  }
  
  _generateGLTFTextures(assets) {
    return [];
  }
  
  _generateGLTFImages(assets) {
    return [];
  }
  
  _convertToGLTFNodes(worldData) {
    return [];
  }
  
  _generateGodotResources(worldData) {
    return {};
  }
}

export default new ExportService();
